# Generated by Django 4.2.21 on 2025-05-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('age', models.CharField(choices=[('0-10', '0-10'), ('11-20', '11-20'), ('21-30', '21-30'), ('31-40', '31-40')], default='0-10', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('Congratulations!', 'Congratulations!'), ('Sorry', 'Sorry'), ('Sad', 'Sad'), ('Enjoy', 'Enjoy'), ('Good Evening', 'Good Evening'), ('Good Morning', 'Good Morning')], default='Good\xa0Morning', max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='MyMessages.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='MyMessages.user')),
            ],
        ),
    ]
